export default function Controls({
  prefs,
  setPrefs,
  onApply,
  staticMode = false,
}) {
  const set = (key, value) =>
    setPrefs((previous) => ({ ...previous, [key]: value }))

  return (
    <section className="controls">
      <div>
        <div className="eyebrow">DECISION CONTROLS</div>
        <h2>Choose what matters.</h2>
      </div>

      {staticMode && (
        <p className="demo-note">
          Static mode uses ranking results pre-generated by the Python service.
        </p>
      )}

      <div className="control-grid">
        <label>
          Max walk
          <input
            type="range"
            min="4"
            max="15"
            value={prefs.maxWalk}
            onChange={(event) =>
              set('maxWalk', Number(event.target.value))
            }
          />
          <strong>{prefs.maxWalk} min</strong>
        </label>

        <label>
          Risk
          <select
            value={prefs.risk}
            onChange={(event) => set('risk', event.target.value)}
          >
            <option value="any">Any</option>
            <option value="low">Low only</option>
            <option value="medium">Low + medium</option>
          </select>
        </label>

        <label>
          Occupancy
          <select
            value={prefs.occupancy}
            onChange={(event) =>
              set('occupancy', event.target.value)
            }
          >
            <option value="any">Any</option>
            <option value="available">Available</option>
            <option value="not_occupied">Not occupied</option>
          </select>
        </label>

        <label>
          Type
          <select
            value={prefs.type}
            onChange={(event) => set('type', event.target.value)}
          >
            <option value="any">Any</option>
            <option value="street_meter">Street meter</option>
            <option value="garage_or_lot">Garage / lot</option>
          </select>
        </label>

        <button onClick={onApply}>
          Re-rank
        </button>
      </div>
    </section>
  )
}
